### ISSUE TITLE
If ReFine can explain heterogeneous graph models？

### ISSUE THREAD

**Issue by MajLuu** [Wuyxin/ReFine#10]
If ReFine can explain heterogeneous graph models? such as: RGCN、HAN，etc...

**Comment by Wuyxin** [comment]
Hi, 

The answer is Yes. And the simplest way to do this is to include the heterogeneous information, i.e., edge types, in edge_attr (e.g., one-hot attributes). Our model will generate edge masks taking edge types into account. c.f., https://github.com/Wuyxin/ReFine/blob/main/explainers/common.py line 60-63. 

I hope it helps.

**Comment by MajLuu** [comment]
Thanks for your reply.
