### ISSUE TITLE
BA3-Motif cannot be created correctly.

### ISSUE THREAD

**Issue by Esperanto-mega** [Wuyxin/ReFine#11]
When I try to train another GNN in BA3-Motif dataset, the 'process' function in 'BA3Motif' class will throw an exception.

Concretely, in 'ba3motif_dataset.py' line 67:

`torch.save(self.collate(data_list[800:]),self.processed_paths[0])`

**Keyerror:15**

'collate' function always causes the Keyerror above.

**Comment by Wuyxin** [comment]
I guess you are using a higher version of torch or torch_geometric. This can be fixed by removing 
```
pos = p,
```
in Line 55 of `ba3motif_dataset.py`. 

Hope that works.

**Comment by Wuyxin** [comment]
Btw it won't affect the training, it just removes the position for visualization, which will be re-generated in the visulization function of Base Explainer.

**Comment by Esperanto-mega** [comment]
Thanks for your reply, my issue has been solved.

My torch verison is 1.11.0, and pyg version is 2.0.4.

**Comment by Esperanto-mega** [comment]
Sorry to bother again, how can I re-generate 'graph.pos' while explaining a given graph and conducting visualization.

Because 'graph.pos' = None.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ying-Xin ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Wuyxin/ReFine] BA3-Motif cannot be created correctly. (Issue #11)





 
Btw it won't affect the training, it just removes the position for visualization, which will be re-generate in the visulization function of Base Explainer.

**Comment by Wuyxin** [comment]
Replacing line 225 in `base.py` as 
```
pos = nx.kamada_kawai_layout(G)
```
will be fine. Or you can find some suitable layout functions in https://networkx.org/documentation/stable/reference/drawing.html

I will update the code later to handle this issue.

**Comment by Esperanto-mega** [comment]
Thanks very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ying-Xin ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 下午4:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Wuyxin/ReFine] BA3-Motif cannot be created correctly. (Issue #11)





 
Replacing line 225 in base.py as
 pos = nx.kamada_kawai_layout(G)  
will be fine. Or you can find some suitable layout function in https://networkx.org/documentation/stable/reference/generated/networkx.drawing.layout.kamada_kawai_layout.html
 
I will update the code later to handle this issue.
