### ISSUE TITLE
How to construct VG-5 Dataset.

### ISSUE THREAD

**Issue by Esperanto-mega** [Wuyxin/ReFine#12]
I have downloaded `visual_genome` from `https://github.com/ranjaykrishna/visual_genome_python_driver`

and `image_data.json` & `synsets.json` from `https://visualgenome.org/api/v0/api_home.html`.

But where can I get the `image_id.json` such as `35.json`, hope to get your reply.

**Comment by Wuyxin** [comment]
Hi, pls download the visual_genome package from the provided google drive link instead https://drive.google.com/file/d/132ziPf2PKqjGoZkqh9194rT17qr3ywN8/

**Comment by Wuyxin** [comment]
This package has been processed.
