### ISSUE TITLE
Question about the EdgeMask

### ISSUE THREAD

**Issue by yuntaod** [Wuyxin/ReFine#13]
Hi Ying-Xin,

Thanks for your excellent work and concise codes!

I am troubled with the mask function that used in  both PG-Explainer and ReFine. Specifically, the mask function consists of the ARMAConv operations and MLPs in common.py,  but I haven't found the descriptions of ARMAConv in paper. So I am wondering that why ARMAConv operations are necessary here?

https://github.com/Wuyxin/ReFine/blob/d8ec5482e8ce2eb37308f1fae1f2dcabe1f33716/explainers/common.py#L36

Looking forward to your reply, much thanks! :)

**Comment by Wuyxin** [comment]
Hi Yuntao,

Thanks for the question. 

Basically, you could use whatever convolutional layers to generate edge masks as long as the conv. layers well capture the local graphical structure, based on which the edge importance values are computed. I think it is convolution-agnostic (that is why we didn't mention it in the paper), and ARMAConv is one of the choices I found suitable to use. 

Hope that helps and feel free to ask more.

**Comment by yuntaod** [comment]
Hi Ying-Xin,

Thanks for your quick reply! However, I am still confused about the mask function. In the original PGExplainer, the input node/graph embeddings of the mask is the output of the GNN that is to be explained. However, I found that the input of the `EdgeMask ` is the node feature of graph, not from the trained GNN. It this is true, I can understand that the conv operations are necessary to capture the local graphical structure.

But  I am wondering that why instead of using the node embeddings from trained GNN for learning the mask, we need to train a new GNN for following structure learning? Is there anything that I missed?

**Comment by Wuyxin** [comment]
You could think of inputting the node embeddings to EdgeMask as node encoder reuse, which asks the explainer model to have certain "representation similarity" with the original GNN. 

The short answer for why we did not use the node embedding is that the target of EdgeMask is to build the correlation between masked features and predictions, and it can do this no matter if the node embedding is available or not, or if it uses MLP or GNN. So it is a choice of implementation, but the target is the same. 

There is actually one more concern that we did not state in our paper: We regard the original GNN as a completely black box, which means we can only get its outputs but the embeddings of the middle layer. This is important if the model is private in real applications (as ppl may somehow infer the model weights from the inner embeddings). Thus the embeddings are not always available.

I think both ways look good to me. Does these make sense to you?

**Comment by yuntaod** [comment]
Sure, I got your point. Thanks again for your reply:)
