### ISSUE TITLE
Performance of backbone GNN

### ISSUE THREAD

**Issue by smiles724** [Wuyxin/ReFine#15]
Hi, thanks for sharing the code, which is well-written.  I re-implemented the GNN on all four datasets. I found that GNNs on MINST/VG/BA3 perform closely to what is reported in the paper. However, the accuracy of the testing set is only 80% for MUTAG, but you claim that it can achieve 100% accuracy.

I know this will not influence the effectiveness of your method. But since I want to follow your work, it is better to figure out whether the backbone GNN is strong enough on MUTAG.  What do you think of this gap?

**Comment by Wuyxin** [comment]
Hi, sry for the misclaim here,  please refer to https://github.com/Wuyxin/ReFine/issues/2

We will create an arxiv version to report the right accuracy, as the camera-ready paper can't be modified.
