### ISSUE TITLE
Performance of other baseline methods 

### ISSUE THREAD

**Issue by smiles724** [Wuyxin/ReFine#16]
Hi, I notice that you provide many scripts of other explanation methods. Did you test the performance of those approaches? If you don't mind, can you give the full results of them?
Thanks.

**Comment by Wuyxin** [comment]
Yeah, we have used other baselines (not reported in this paper, though). Please refer to: https://openreview.net/pdf?id=nzKv5vxZfge (Fig. 3 & Tab. 1)

We actually pick up the strongest baselines to compare with ReFine in this work, but we can definitely do this for all of them.

**Comment by smiles724** [comment]
Thanks for your response. This is really excellent work!
