### ISSUE TITLE
ACC-AUC on BA3-Motif

### ISSUE THREAD

**Issue by smiles724** [Wuyxin/ReFine#17]
Hi, I want to ask something regarding the performance on BA3-motif.

You reported that Refiner achieve an ACC-AUC of 0.630. However, in your log file, the highest ACC-AUC of Refiner is only 0.612. Is anything wrong with the log you uploaded?

**Comment by Wuyxin** [comment]
The final evaluation is in [ba3_results.json](https://github.com/Wuyxin/ReFine/blob/main/results/ba3_results.json) (line 181), which is 0.631.

PS: we rerun all programs after publishing to ensure the reproductivity so the results might be slightly different (a bit higher than reported).

**Comment by smiles724** [comment]
OK, perhaps it was my fault to fail to reproduce the results. I will try it again.
